# draw_tree.py

import plotly.express as px

species = [
    {"name": "Chondrichthyes", "parent": ""},
    {"name": "Elasmobrancii", "parent": "Chondrichthyes"},
    {"name": "Batoidea", "parent": "Elasmobrancii"},
    {"name": "Selacii (sharks)", "parent": "Elasmobrancii"},
    {"name": "Holicephali", "parent": "Chondrichthyes"},
    {"name": "Genus Chimaera", "parent": "Holicephali"},
    {"name": "Spiny dogfish<br>Squalus acanthias", "parent": "Selacii (sharks)"},
    {"name": "Rajiformes (skates)", "parent": "Batoidea"},
    {"name": "Gurgesiellidae (pygmy skates)", "parent": "Rajiformes (skates)"},
    {"name": "Roughnose legskate", "parent": "Gurgesiellidae (pygmy skates)"},
    {"name": "Arhynchobatidae (softnose skates)", "parent": "Rajiformes (skates)"},
    {"name": "Alaska skate<br>Bathyraja parmifera", "parent": "Arhynchobatidae (softnose skates)"},
    {"name": "Peacock skate<br>Pavoraja nitida", "parent": "Arhynchobatidae (softnose skates)"},
    {"name": "Myliobatiformes (stingrays)", "parent": "Batoidea"},
    {"name": "Dasyatidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Diamond stingray<br>Hypanus dipterurus", "parent": "Dasyatidae"},
    {"name": "Blue-spotted maskray<br>Neotrygon kuhlii", "parent": "Dasyatidae"},
    {"name": "Roughnose stingray<br>Pastinachus solocirostris", "parent": "Dasyatidae"},
    {"name": "Blue-spotted ribbontail<br>Taeniura lymma", "parent": "Dasyatidae"},
    {"name": "Porcupine ray<br>Urogymnus asperrimus", "parent": "Dasyatidae"},
    {"name": "Gymnuridae (butterfly rays)", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Longsnout butterfly ray<br>Gymnura crebripunctata", "parent": "Gymnuridae (butterfly rays)"},
    {"name": "Hexatrygonidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Six-gill stingray<br>Hexatrygon bickelli", "parent": "Hexatrygonidae"},
    {"name": "Myliobatidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Spinetail devil ray<br>Mobula japanica", "parent": "Myliobatidae"},
    {"name": "Potamotrygonidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Porcupine river stingray<br>Potamotrygon hystrix", "parent": "Potamotrygonidae"},
    {"name": "Ocellated eagle ray<br>Aetobatus ocellatus", "parent": "Myliobatidae"},
    {"name": "Australian bull ray<br>Myliobatis australis", "parent": "Myliobatidae"},
    {"name": "Torpediniformes (electric rays)", "parent": "Batoidea"},
    {"name": "Narcinidae", "parent": "Torpediniformes (electric rays)"},
    {"name": "Tasmanian numbfish<br>Narcine tasmaniensis", "parent": "Narcinidae"},
    {"name": "Blind electric ray<br>Typhlonarke aysoni", "parent": "Narcinidae"},
    {"name": "Plesiobatidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Deepwater stingray<br>Plesiobatis daviesi", "parent": "Plesiobatidae"},
    {"name": "Platyrhinidae", "parent": "Torpediniformes (electric rays)"},
    {"name": "Thornback<br>Platyrhinoidis triseriata", "parent": "Platyrhinidae"},
    {"name": "Chupare stingray<br>Styracura schmardae", "parent": "Potamotrygonidae"},
    {"name": "Rhinopristiformes", "parent": "Batoidea"},
    {"name": "Pristidae", "parent": "Rhinopristiformes"},
    {"name": "Dwarf sawfish<br>Pristis clavata", "parent": "Pristidae"},
    {"name": "Rajidae", "parent": "Rajiformes (skates)"},
    {"name": "Thorny skate<br>Amblyraja radiata", "parent": "Rajidae"},
    {"name": "Genus Okamejei", "parent": "Rajidae"},
    {"name": "Rhinidae", "parent": "Rhinopristiformes"},
    {"name": "Bowmouth guitarfish<br>Rhina ancylostoma", "parent": "Rhinidae"},
    {"name": "Rhinobatidae", "parent": "Rhinopristiformes"},
    {"name": "Speckled guitarfish<br>Rhinobatos glaucostigma", "parent": "Rhinobatidae"},
    {"name": "Eastern fiddler ray<br>Trygonorrhina fasciata", "parent": "Rhinobatidae"},
    {"name": "Trygonorrhinidae", "parent": "Rhinopristiformes"},
    {"name": "Banded guitarfish<br>Zapteryx exasperata", "parent": "Trygonorrhinidae"},
    {"name": "Cownose ray<br>Rhinoptera steindachneri", "parent": "Myliobatidae"},
    {"name": "Giant guitarfish<br>Rhynchobatus djiddensis", "parent": "Rhinidae"},
    {"name": "Torpedinidae", "parent": "Torpediniformes (electric rays)"},
    {"name": "Shorttail torpedo<br>Torpedo macneilli", "parent": "Torpedinidae"},
    {"name": "Urolophidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Crossback stingaree<br>Urolophus cruciatus", "parent": "Urolophidae"},
    {"name": "Urotrygonidae", "parent": "Myliobatiformes (stingrays)"},
    {"name": "Round stingray<br>Urobatis halleri", "parent": "Urotrygonidae"},
    {"name": "Zanobatidae", "parent": "Rhinopristiformes"},
    {"name": "Striped panray<br>Zanobatus schoenleinii", "parent": "Zanobatidae"},
    {"name": "Round skate<br>Rajella fyllae", "parent": "Rajidae"},
    {"name": "Glaucostegidae", "parent": "Rhinopristiformes"},
    {"name": "Common shovelnose ray<br>Glaucostegus typus", "parent": "Glaucostegidae"},
    {"name": "Fanray<br>Platyrhina sinensis", "parent": "Platyrhinidae"},
    {"name": "Genus Atlantoraja", "parent": "Arhynchobatidae (softnose skates)"},
    {"name": "Genus Heterodontus", "parent": "Selacii (sharks)"},
    {"name": "Genus Scyliorhinus", "parent": "Selacii (sharks)"},
    {"name": "Genus Mustelus", "parent": "Selacii (sharks)"},
    {"name": "Goblin shark<br>Mitsukurina owstoni", "parent": "Selacii (sharks)"},
]

names = [x['name'] for x in species]
parents = [x['parent'] for x in species]

fig = px.treemap(
    names = names,
    parents = parents,
    
)

fig.update_traces(root_color="lightgrey", marker=dict(cornerradius=5))
fig.show()
